### ISSUE TITLE
Code release timeline?

### ISSUE THREAD

**Issue by johnwlambert** [aminshabani/extreme-indoor-sfm#2]
Hi authors, very nice work and excellent paper. Was just wondering what the timeline is for release? Would love to try out the method and code. Thanks!

**Comment by johnwlambert** [comment]
@aminshabani Again, really nice job with the paper. Two other quick questions from a quick read:

1. How does the 47% top-1 or 78% top-5 localization success rate fit into the ablation study in Table 1 (under what settings from Table 1 were they achieved)?
2. I was a bit confused about Footnote #4:
```
Door/window type classification is not reliable and we treat all the door/window detections
(except for “Window”) as the same doors. The full door/window types are utilized by baseline
methods in the experiments.
```
Does this mean that annotated or predicted semantic door/window types are used at test time?

Many thanks! Congratulations again on the ICCV paper.

**Comment by aminshabani** [comment]
Hi, 
Thank you for your kind comments.
Regarding the code, unfortunately, we don't have any specific timeline but I will try to publish them as soon as possible and I will also update it here to inform you.

For the questions:
1. Each value in the second row of Table 1 is the average of the corresponding success rates (average of K_1 to k_5) in Figure 6.
2. The predicted semantic door/window types are used at the test time. Footnote #4 refers to the point that the predicted types for the Door/Window which includes  "Door/Glass-door/Frame/Window/Kitchencounter/Closet", is not completely reliable (for example it is hard to distinguish an open door from a frame, or a closet door from a closed door with the similar texture) and therefore, we consider all of the doors as the same for generating the candidate arrangements.

Thanks again, please let me know if you had any further questions.

**Comment by johnwlambert** [comment]
Thanks @aminshabani, makes sense. A few more questions, if you have a minute:

(1) What is the license for the 286-house dataset you all introduced for your paper? And any rough estimate on when the data will be available (like next week, or next month, or in a few months)?
(2) What is the average Extremal SfM runtime per home? (this might have been in the paper and I missed it)

**Comment by aminshabani** [comment]
Thank you John and sorry I missed your comment. The code is currently available with a few houses as the example input. We are still working on getting permission to publish the full dataset.

The current average runtime per house varies from a few minutes to hours based on the number of panoramas and the number of doors in each Nadir Image. This is actually one of the main weaknesses of our work as the arrangement generator considers all of the possible arrangements (this means that runtime exponentially increases based on the number of rooms and doors). Although this can be highly improved by having the rotations of panoramas or having a reliable door classification and filtering doors by their types, we are still working to provide a better method to overcome this issue.

Thanks
